[package]
name = "udon"
version = "0.1.0"
authors = ["Hajime Suzuki <suzuki.hajime.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13"
log = "0.4"

